#!/bin/bash
# This script gets demo templates from Nuxeo server and extract them so they can by use by nuxeo.conf.

if test ! ${VARIABLES_INITIALIZED}
then
	echo "Initializing variables"	
	source ./99-initScriptVariables.sh || exit 1
fi

cd ${NUXEO_DEMO_PARENT_DIR}/${NUXEO_DEMO_DIR} || exit 1


if test ! -e ${NUXEO_CONF}
then
	echo "Nuxeo Conf cannot be found at expected location, please edit the script 99-initScriptVariables to locate nuxeo.conf file"
	echo ${NUXEO_CONF}
	exit
fi

if test ! -d ${NUXEO_SERVER_DIR}
then
	echo "No nuxeo server found at expected location,please edit the script 99-initScriptVariables to locate server dir"
	echo ${NUXEO_SERVER_DIR}
	exit
fi

echo "getting fresh distrib from Nuxeo servers"
wget -N "${NUXEO_DISTRIB_DOWNLOAD_LINK}${NUXEO_DISTRIB}.zip"|| exit 1

if test -d ${NUXEO_DEMO_PARENT_DIR}/${NUXEO_DEMO_DIR}/distribution
then
	echo "Older distrib found, resetting it"
	rm -r ${NUXEO_DEMO_PARENT_DIR}/${NUXEO_DEMO_DIR}/distribution/ || exit 1
fi

mkdir distribution || exit 1


if test -d ${NUXEO_DISTRIB}
then
	rm -r ${NUXEO_DISTRIB} || exit 1
fi

echo "unzipping distribution"
unzip -q ${NUXEO_DISTRIB}.zip

if test ! -e nuxeo.original.backup.conf
then
	echo "Backup of original nuxeo conf"
	cp ${NUXEO_CONF} nuxeo.conf.backup.original || exit 1
else
	echo "Restoring original nuxeo conf"
	cp nuxeo.conf.backup.original ${NUXEO_CONF} || exit 1
fi

echo "Stopping possibly running nuxeo server"
${NUXEO_SERVER_DIR}/bin/nuxeoctl stop

echo "Updating nuxeo.conf"
ORIGINAL_LINE=`grep "^nuxeo.templates=" ${NUXEO_CONF}`
echo $ORIGINAL_LINE

if test -d ${NUXEO_DEMO_PARENT_DIR}/${NUXEO_DEMO_DIR}/${NUXEO_DEMO_TEMPLATES}/custom
then
	NEW_LINE=nuxeo.templates=postgresql,${NUXEO_DEMO_PARENT_DIR}/${NUXEO_DEMO_DIR}/${NUXEO_DEMO_TEMPLATES}/custom
else 
	echo "It seems there is no custom templates deployed on your system, you may want to run the script 03-updateBackupTemplatesFromWeb first (it's not mandatory)"
	NEW_LINE=nuxeo.templates=postgresql
fi
echo $NEW_LINE
sed s:${ORIGINAL_LINE}:"${NEW_LINE}": <nuxeo.conf.backup.original> ${NUXEO_CONF} || exit 1

NUXEO_DATA_DIR=`grep "^nuxeo.data.dir=" $NUXEO_CONF | cut -d= -f2`
echo "Deleting current data"
rm -R ${NUXEO_DATA_DIR}/*
echo "Deleting current server"
rm -R ${NUXEO_SERVER_DIR}/*

echo "Copying fresh distrib"
mv ${NUXEO_DISTRIB}/* ${NUXEO_SERVER_DIR}/
rmdir ${NUXEO_DISTRIB}

echo $NUXEO_SERVER_DIR
echo $NUXEO_CONF

echo "Initializing server and installing default packages (dm, dam, social collab)"
${NUXEO_SERVER_DIR}/bin/nuxeoctl mp-init
${NUXEO_SERVER_DIR}/bin/nuxeoctl mp-init mp-remove nuxeo-cmf
${NUXEO_SERVER_DIR}/bin/nuxeoctl mp-list | grep downloaded |cut -f2|cut -d ' ' -f1 |xargs ${NUXEO_SERVER_DIR}/bin/nuxeoctl mp-install

if test -e ${NUXEO_DEMO_PARENT_DIR}/instance.clid
then
	echo "Instance.clid found, copying it on the server, and hotfixing the server"
	cp ${NUXEO_DEMO_PARENT_DIR}/instance.clid ${NUXEO_DATA_DIR}
	${NUXEO_SERVER_DIR}/bin/nuxeoctl mp-hotfix --accept=true || exit 1
else
	echo "No instance.clid found, the hotfixes will not be installed on the server. Altough not mandatory, it is highly recommanded. The instance.clid is looked for in the parent of the nuxeo_demo folder. In your case in:"
	echo ${NUXEO_DEMO_PARENT_DIR}
	echo "instance.clid files can be generated by registering another instance and getting the instance.clid file."
fi

mkdir distribution/server || exit 1
mkdir distribution/data || exit 1

cp -r $NUXEO_SERVER_DIR/* distribution/server/ || exit 1
cp -r ${NUXEO_DATA_DIR}/* distribution/data/ || exit 1
cp ${NUXEO_CONF} nuxeo.conf.backup || exit 1

echo "A fresh updated server is now available in demo data. A proper reset should be done now to reset the server"







