#!/bin/bash

# Installation can take time.
# You can tail -F /var/log/nuxeo_install.log to see basic install progress
# You can tail -F /var/log/syslog to see the full startup and check for errors

source /etc/profile.d/load_env.sh

INSTALL_LOG="/var/log/nuxeo_install.log"

COMPOSE_REPO="https://github.com/nuxeo-sandbox/nuxeo-presales-docker"
COMPOSE_DIR="/home/ubuntu/nuxeo-presales-docker"

NUXEO_BASE_DIR="/var/lib/nuxeo"
NUXEO_CONF_DIR="${NUXEO_BASE_DIR}/conf"
NUXEO_DATA_DIR="${NUXEO_BASE_DIR}/data"
NUXEO_LOG_DIR="${NUXEO_BASE_DIR}/log"
NUXED_ENV="${NUXEO_BASE_DIR}/env"

STUDIO_USERNAME="nuxeo_presales"

echo "Nuxeo Presales Installation Script Starting [${DNS_NAME}]" > ${INSTALL_LOG}

# Check DNS Name
if [ -z "${DNS_NAME}" ]
then
  DNS_NAME=${STACK_ID}
  echo "Warning: DNS Name is not set, using stack id: ${STACK_ID}" | tee -a ${INSTALL_LOG}
fi

# Increase open files limit
echo '*       soft    nofile      4096' >> /etc/security/limits.conf
echo '*       hard    nofile      8192' >> /etc/security/limits.conf

# Set the hostname & domain
echo "${DNS_NAME}" > /etc/hostname
hostname ${DNS_NAME}
echo "Domains=cloud.nuxeo.com" >> /etc/systemd/resolved.conf

# Upgrade packages and install apache, ssh, ...
echo "Nuxeo Presales Installation Script: Apache, upgrade packages, etc." | tee -a ${INSTALL_LOG}
export DEBIAN_FRONTEND=noninteractive
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
apt-get update
apt-get -q -y upgrade
apt-get -q -y install apache2 apt-transport-https openssh-server openssh-client vim jq git \
                      ca-certificates curl software-properties-common python3-pip
echo "Please wait a few minutes for you instance installation to complete" > /var/www/html/index.html

# Install JA fonts
# apt-get -q -y install fonts-takao

# Install latest aws cli using pip
pip3 install awscli --upgrade --user
export PATH=$PATH:~/.local/bin/
echo "Nuxeo Presales Installation Script: Apache, upgrade packages, etc. => DONE" | tee -a ${INSTALL_LOG}

# Install additional Repos
echo "Nuxeo Presales Installation Script: Install Repositories" | tee -a ${INSTALL_LOG}
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository -y universe
add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
add-apt-repository -y ppa:certbot/certbot
apt-get update
echo "Nuxeo Presales Installation Script: Install Repositories => DONE" | tee -a ${INSTALL_LOG}

# Install docker
echo "Nuxeo Presales Installation Script: Install Docker" | tee -a ${INSTALL_LOG}
apt-get -q -y remove docker docker-engine docker.io
apt-get -q -y install docker-ce
pip3 install --system docker-compose
echo "Nuxeo Presales Installation Script: Install Docker => DONE" | tee -a ${INSTALL_LOG}

# Install Certbot
echo "Nuxeo Presales Installation Script: Install Certbot" | tee -a ${INSTALL_LOG}
apt-get -q -y install certbot python-certbot-apache
echo "Nuxeo Presales Installation Script: Install Certbot => DONE" | tee -a ${INSTALL_LOG}

# Install Nuxeo
echo "Nuxeo Presales Installation Script: Install Nuxeo" | tee -a ${INSTALL_LOG}
# Add ubuntu user to docker group
usermod -aG docker ubuntu

mkdir -p ${COMPOSE_DIR} ${NUXEO_CONF_DIR} ${NUXEO_DATA_DIR} ${NUXEO_LOG_DIR}
git clone ${COMPOSE_REPO} ${COMPOSE_DIR}

chown -R ubuntu:ubuntu ${NUXEO_BASE_DIR}
echo "Nuxeo Presales Installation Script: Install Nuxeo => DONE" | tee -a ${INSTALL_LOG}

echo "Nuxeo Presales Installation Script: Configure Nuxeo
" | tee -a ${INSTALL_LOG}
# Link old log location to new
ln -s ${NUXEO_LOG_DIR} /var/log/nuxeo

# Add default conf.d files
cp ${COMPOSE_DIR}/conf.d/*.conf ${NUXEO_CONF_DIR}

# Secrets for instance
MAIL_PASS=$(aws secretsmanager get-secret-value --secret-id workmail_default_password --region us-west-2 | jq -r '.SecretString|fromjson|.workmail_default_password')

# Support old style of creating a bucket
S3_BUCKET="${STACK_ID}-bucket"
S3_PREFIX="binary_store/"
S3_UPLOAD_PREFIX="upload/"

if [[ "${S3BUCKET}" == "Shared" ]]; then
  S3_BUCKET="${REGION}-demo-bucket"
  S3_PREFIX="${STACK_ID}/binary_store/"
  S3_UPLOAD_PREFIX="${STACK_ID}/upload/"
fi

# Write system configuration
cat << EOF > ${NUXEO_CONF_DIR}/system.conf
# Host Configuration
session.timeout=600
nuxeo.url=https://${DNS_NAME}.cloud.nuxeo.com/nuxeo

# Mail Configuration
mail.transport.password=${MAIL_PASS}
mail.transport.host=smtp.mail.us-east-1.awsapps.com
mail.transport.port=465
mail.transport.user=no-reply@nuxeo-demo.awsapps.com
mail.transport.auth=true
mail.from=no-reply@nuxeo-demo.awsapps.com
mail.smtp.ssl.enable=true
mail.transport.protocol=smtps
nuxeo.notification.eMailSubjectPrefix=[Nuxeo]

# S3 Configuration
nuxeo.s3storage.useDirectUpload=true
nuxeo.s3storage.directdownload.expire=3600
nuxeo.s3storage.directdownload=true

nuxeo.s3storage.bucket=${S3_BUCKET}
nuxeo.s3storage.bucket_prefix=${S3_PREFIX}
nuxeo.s3storage.region=${REGION}
nuxeo.s3storage.transient.roleArn=${UPLOAD_ROLE_ARN}
nuxeo.s3storage.transient.bucket=${S3_BUCKET}
nuxeo.s3storage.transient.bucket_prefix=${S3_UPLOAD_PREFIX}
EOF

# Register the nuxeo instance
if [ -n "${NX_STUDIO}" ]; then
  echo "Nuxeo Presales Installation Script: Install Studio project" | tee -a ${INSTALL_LOG}
  echo "$(date) Register Nuxeo Instance ${NX_STUDIO}" | tee -a ${INSTALL_LOG}

  AUTO_PACKAGES="nuxeo-web-ui marketplace-disable-studio-snapshot-validation"
  if [[ "${S3BUCKET}" == "true" || "${S3BUCKET}" == "Create" || "${S3BUCKET}" == "Shared" ]]; then
    AUTO_PACKAGES="${AUTO_PACKAGES} amazon-s3-online-storage amazon-s3-direct-upload"
  fi

  CREDENTIALS=$(aws secretsmanager get-secret-value --secret-id connect_shared_presales_credential --region us-west-2 | jq -r '.SecretString|fromjson|.connect_presales_pwd')
  cat << EOF > ${NUXEO_ENV}
APPLICATION_NAME=${NX_STUDIO}
NUXEO_REGISTRY=docker.packages.nuxeo.com
NUXEO_IMAGE=nuxeo/nuxeo
NUXEO_VERSION=latest
NUXEO_PORT=8080
NUXEO_PACKAGES=${NX_STUDIO}-0.0.0-SNAPSHOT ${AUTO_PACKAGES} ${NUXEO_PACKAGES}

STUDIO_USERNAME=${STUDIO_USERNAME}
STUDIO_CREDENTIALS=${CREDENTIALS}
EOF
  #nuxeoctl register nuxeo_presales ${NX_STUDIO} "dev" "AWS_${STACK_ID}" "${CREDENTIALS}" | tee -a ${INSTALL_LOG}
  #nuxeoctl mp-hotfix --accept true | tee -a ${INSTALL_LOG}
  #nuxeoctl mp-install nuxeo-web-ui marketplace-disable-studio-snapshot-validation --accept true | tee -a ${INSTALL_LOG}
  #if [[ "${S3BUCKET}" == "true" || "${S3BUCKET}" == "Create" || "${S3BUCKET}" == "Shared" ]]; then
  #  nuxeoctl mp-install amazon-s3-online-storage amazon-s3-direct-upload --accept true | tee -a ${INSTALL_LOG}
  #fi
  #nuxeoctl mp-install ${NX_STUDIO}-0.0.0-SNAPSHOT --accept true | tee -a ${INSTALL_LOG}
  echo "Starting Nuxeo..." | tee -a ${INSTALL_LOG}

  docker-compose --project-directory ${COMPOSE_DIR} up -d --no-color | tee -a ${INSTALL_LOG}

  echo "Nuxeo Presales Installation Script: Install Studio project => DONE" | tee -a ${INSTALL_LOG}
fi
echo "Nuxeo Presales Installation Script: Configure Nuxeo => DONE" | tee -a ${INSTALL_LOG}

echo "Nuxeo Presales Installation Script: Install Misc. (ffmpeg, etc.)" | tee -a ${INSTALL_LOG}
# Update some defaults
update-alternatives --set editor /usr/bin/vim.basic

#apt-get install -q -y mediainfo ffmpeg x264 x265 figlet atop

apt-get -y clean
echo "Nuxeo Presales Installation Script: Install Misc. (ffmpeg, etc.) => DONE" | tee -a ${INSTALL_LOG}

# Configure reverse-proxy
cat << EOF > /etc/apache2/sites-available/nuxeo.conf
<VirtualHost _default_:80>

    ServerName  ${DNS_NAME}.cloud.nuxeo.com

    CustomLog /var/log/apache2/nuxeo_access.log combined
    ErrorLog /var/log/apache2/nuxeo_error.log

    Redirect permanent / https://${DNS_NAME}.cloud.nuxeo.com/

</VirtualHost>

<VirtualHost _default_:443 >

    ServerName  ${DNS_NAME}.cloud.nuxeo.com

    CustomLog /var/log/apache2/nuxeo_access.log combined
    ErrorLog /var/log/apache2/nuxeo_error.log

    DocumentRoot /var/www

    ProxyRequests   Off
     <Proxy * >
        Order allow,deny
        Allow from all
     </Proxy>

    <Location /kibana>
      AuthUserFile /etc/apache2/passwords
      AuthName authorization
      AuthType Basic
      require valid-user
    </Location>

    RewriteEngine   On
    RewriteRule ^/$ /nuxeo/ [R,L]
    RewriteRule ^/nuxeo$ /nuxeo/ [R,L]
    RewriteRule ^/kibana$ /kibana/ [R,L]

    ProxyPass           /nuxeo/         http://localhost:8080/nuxeo/
    ProxyPass           /ARender/       http://localhost:8080/ARender/
    ProxyPass           /kibana/        http://localhost:5601/
    ProxyPassReverse    /nuxeo/         http://localhost:8080/nuxeo/
    ProxyPassReverse    /ARender/       http://localhost:8080/ARender/
    ProxyPassReverse    /kibana/        http://localhost:5601/
    ProxyPreserveHost   On

    # WSS
    ProxyPass         /_vti_bin/     http://localhost:8080/_vti_bin/
    ProxyPass         /_vti_inf.html http://localhost:8080/_vti_inf.html
    ProxyPassReverse  /_vti_bin/     http://localhost:8080/_vti_bin/
    ProxyPassReverse  /_vti_inf.html http://localhost:8080/_vti_inf.html

    RequestHeader   append nuxeo-virtual-host "https://${DNS_NAME}.cloud.nuxeo.com/"

    # Retain TLS1.1 for backwards compatibility until Jan 2020
    # These must be *after* the Certbot entry
    #XXX SSLProtocol all -SSLv2 -SSLv3 -TLSv1
    # SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
    # Enable high ciphers for 3rd party security scanners
    #XXX SSLCipherSuite HIGH:!aNULL:!MD5:!3DES

    ## BEGIN SUPINT-655 ##
    <Location "/nuxeo/incl">
      RewriteRule .* - [R=404,L,NC]
    </Location>
    ## END SUPINT-655 ##
</VirtualHost>
EOF

# Add gzip compression for the REST API
cat > /etc/apache2/mods-available/deflate.conf <<EOF
<IfModule mod_deflate.c>
        <IfModule mod_filter.c>
                # these are known to be safe with MSIE 6
                AddOutputFilterByType DEFLATE text/html text/plain text/xml

                # everything else may cause problems with MSIE 6
                AddOutputFilterByType DEFLATE text/css
                AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript
                AddOutputFilterByType DEFLATE application/rss+xml
                AddOutputFilterByType DEFLATE application/xml
                AddOutputFilterByType DEFLATE application/json
        </IfModule>
</IfModule>
EOF

a2enmod proxy proxy_http rewrite ssl headers
a2dissite 000-default
a2ensite nuxeo
KIBANA_PASS=$(aws secretsmanager get-secret-value --secret-id kibana_default_password --region us-west-2 | jq -r '.SecretString|fromjson|.kibana_default_password')
htpasswd -b -c /etc/apache2/passwords kibana "${KIBANA_PASS}"
apache2ctl -k graceful

# Enable SSL certs
echo "Nuxeo Presales Installation Script: Enable Certbot Certificate" | tee -a ${INSTALL_LOG}
certbot -q --apache --redirect --hsts --uir --agree-tos -m wwpresales@nuxeo.com -d ${DNS_NAME}.cloud.nuxeo.com | tee -a ${INSTALL_LOG}

echo "Nuxeo Presales Installation Script: Setup profile, ubuntu, etc." | tee -a ${INSTALL_LOG}

#fix imagemagick Policy
#wget https://raw.githubusercontent.com/nuxeo/presales-vmdemo/${NX_BRANCH}/ImageMagick/policy.xml -O /etc/ImageMagick-6/policy.xml

#set up ubuntu user
cat << EOF >> /home/ubuntu/.profile
export TERM="xterm-color"
export PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\]\$ '
alias dir='ls -alFGh'
alias hs='history'
alias mytail='tail -F /var/log/nuxeo/server.log'
alias vilog='vi /var/log/nuxeo/server.log'
alias mydu='du -sh */'
figlet $DNS_NAME.cloud.nuxeo.com
EOF

# Set up vim for ubuntu user
cat << EOF > /home/ubuntu/.vimrc
" Set the filetype based on the file's extension, but only if
" 'filetype' has not already been set
au BufRead,BufNewFile *.conf setfiletype conf
EOF
echo "Nuxeo Presales Installation Script: Setup profile, ubuntu, etc. => DONE" | tee -a ${INSTALL_LOG}

echo "Nuxeo Presales Installation Script Complete" | tee -a ${INSTALL_LOG}
