#!/bin/bash

# Installation can take time.
# You can tail -F /var/log/nuxeo_install.log to see basic install progress
# You can tail -F /var/log/syslog to see the full startup and check for errors

source /etc/profile.d/load_env.sh

INSTALL_LOG="/var/log/nuxeo_install.log"
echo "Nuxeo Presales Installation Script Starting" > ${INSTALL_LOG}

ES_VERSION="6.5.4"

# Increase open files limit
echo '*       soft    nofile      4096' >> /etc/security/limits.conf
echo '*       hard    nofile      8192' >> /etc/security/limits.conf

# Add the nuxeo repository to the repository list
code=$(lsb_release -cs)
echo "deb http://apt.nuxeo.org/ $code releases" > /etc/apt/sources.list.d/nuxeo.list

# Register the nuxeo key
wget -q -O- http://apt.nuxeo.org/nuxeo.key | apt-key add -

# Pre-accept Sun Java license & set Nuxeo options
echo nuxeo nuxeo/bind-address select 127.0.0.1 | debconf-set-selections
echo nuxeo nuxeo/http-port select 8080 | debconf-set-selections
echo nuxeo nuxeo/database select Autoconfigure PostgreSQL | debconf-set-selections

# Upgrade packages and install apache, ssh, ...
echo "Nuxeo Presales Installation Script: Apache, upgrade packages, etc." | tee -a ${INSTALL_LOG}
export DEBIAN_FRONTEND=noninteractive
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
apt-get update
apt-get -q -y upgrade
apt-get -q -y install apache2
echo "Please wait a few minutes for you instance installation to complete" > /var/www/html/index.html
apt-get -q -y install openssh-server openssh-client vim
echo "Nuxeo Presales Installation Script: Apache, upgrade packages, etc. => DONE" | tee -a ${INSTALL_LOG}

# Install JA fonts
apt-get -q -y install fonts-takao

# Install Java
echo "Nuxeo Presales Installation Script: Install Java" | tee -a ${INSTALL_LOG}
apt-get -q -y install openjdk-11-jdk
echo "Nuxeo Presales Installation Script: Install Java => DONE" | tee -a ${INSTALL_LOG}

#install elasticsearch
echo "Nuxeo Presales Installation Script: Install Elasticsearch" | tee -a ${INSTALL_LOG}
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
apt-get -q -y install apt-transport-https
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb.sha512
shasum -a 512 -c elasticsearch-$ES_VERSION.deb.sha512
dpkg -i elasticsearch-$ES_VERSION.deb
/bin/systemctl daemon-reload
/bin/systemctl enable elasticsearch.service
/usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-kuromoji
/usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
#set default ES heap to 1G
sed -i 's/Xms2g/Xms1g/g' /etc/elasticsearch/jvm.options
sed -i 's/Xmx2g/Xmx1g/g' /etc/elasticsearch/jvm.options

service elasticsearch start
echo "Nuxeo Presales Installation Script: Install Elasticsearch => DONE" | tee -a ${INSTALL_LOG}

#install docker
echo "Nuxeo Presales Installation Script: Install Docker" | tee -a ${INSTALL_LOG}
apt-get -q -y remove docker docker-engine docker.io
apt-get -q -y install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update
apt-get -q -y install docker-ce
echo "Nuxeo Presales Installation Script: Install Docker => DONE" | tee -a ${INSTALL_LOG}

# Install Nuxeo
echo "Nuxeo Presales Installation Script: Install Nuxeo" | tee -a ${INSTALL_LOG}
apt-get -q -y install nuxeo
service nuxeo stop
echo "Nuxeo Presales Installation Script: Install Nuxeo => DONE" | tee -a ${INSTALL_LOG}

#add nuxeo user to docker group
sudo usermod -aG docker nuxeo

#skip wizard
sed -i '/nuxeo.wizard.done=false/d' /etc/nuxeo/nuxeo.conf
sed -i '1inuxeo.wizard.done=true' /etc/nuxeo/nuxeo.conf
#enable dev mode
sed -i '1iorg.nuxeo.dev=true' /etc/nuxeo/nuxeo.conf
#use standalone elasticsearch
sed -i '1ielasticsearch.addressList=localhost:9200' /etc/nuxeo/nuxeo.conf
#enable remote debugging
sed -i '1iJAVA_OPTS=$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n' /etc/nuxeo/nuxeo.conf

echo "Nuxeo Presales Installation Script: Install Misc. (ffmpeg, etc.)" | tee -a ${INSTALL_LOG}
# Update some defaults
update-alternatives --set editor /usr/bin/vim.basic

sudo apt-get install -y mediainfo ffmpeg x264 x265 figlet atop jq

# Install latest aws cli using pip
sudo apt-get install -y python3-pip
pip3 install awscli --upgrade --user
export PATH=$PATH:~/.local/bin/

apt-get -y clean
echo "Nuxeo Presales Installation Script: Install Misc. (ffmpeg, etc.) => DONE" | tee -a ${INSTALL_LOG}

# Configure reverse-proxy
cat << EOF > /etc/apache2/sites-available/nuxeo.conf
<VirtualHost _default_:80>

    CustomLog /var/log/apache2/nuxeo_access.log combined
    ErrorLog /var/log/apache2/nuxeo_error.log

    DocumentRoot /var/www

    ProxyRequests Off
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>

    RewriteEngine On
    RewriteRule ^/$ /nuxeo/ [R,L]
    RewriteRule ^/nuxeo$ /nuxeo/ [R,L]

    ProxyPass        /nuxeo/ http://localhost:8080/nuxeo/
    ProxyPassReverse /nuxeo/ http://localhost:8080/nuxeo/
    ProxyPreserveHost On

</VirtualHost>
EOF
a2enmod proxy proxy_http rewrite
a2dissite 000-default
a2ensite nuxeo
apache2ctl -k graceful

echo "Nuxeo Presales Installation Script: Setup profile, ubuntu, etc." | tee -a ${INSTALL_LOG}

#fix imagemagick Policy
wget https://raw.githubusercontent.com/nuxeo/presales-vmdemo/master/ImageMagick/policy.xml -O /etc/ImageMagick-6/policy.xml

#set up profile for nuxeo user
cat << EOF > /var/lib/nuxeo/server/.profile
export NUXEO_CONF=/etc/nuxeo/nuxeo.conf
cd /var/lib/nuxeo/server/bin
echo  "Hi, nuxeo user. NUXEO_CONF is defined, and you are in /bin, ready to ./nuxeoctl"
alias ll='ls -al'
alias la='ls -a'
alias ..='cd ..'
export TERM="xterm-color"
export PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\]\$ '
alias dir='ls -alFGh'
alias hs='history'
alias mytail='tail -F /var/log/nuxeo/server.log'
alias vilog='vi /var/log/nuxeo/server.log'
figlet -t $STACK_ID.cloud.nuxeo.com
EOF
chown nuxeo:nuxeo /var/lib/nuxeo/server/.profile

#set up vim for nuxeo user
cat << EOF > /var/lib/nuxeo/server/.vimrc
" Set the filetype based on the file's extension, but only if
" 'filetype' has not already been set
au BufRead,BufNewFile *.conf setfiletype conf
EOF
chown nuxeo:nuxeo /var/lib/nuxeo/server/.vimrc

#set up ubuntu user
cat << EOF >> /home/ubuntu/.profile
export TERM="xterm-color"
export PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\]\$ '
alias dir='ls -alFGh'
alias hs='history'
alias mytail='tail -F /var/log/nuxeo/server.log'
alias vilog='vi /var/log/nuxeo/server.log'
alias mydu='du -sh */'
figlet $STACK_ID.cloud.nuxeo.com
EOF

#set up vim for ubuntu user
cat << EOF > /home/ubuntu/.vimrc
" Set the filetype based on the file's extension, but only if
" 'filetype' has not already been set
au BufRead,BufNewFile *.conf setfiletype conf
EOF
echo "Nuxeo Presales Installation Script: Setup profile, ubuntu, etc. => DONE" | tee -a ${INSTALL_LOG}

echo "Nuxeo Presales Installation Script Complete" | tee -a ${INSTALL_LOG}
